<?php


namespace Magenest\Cybergame\Model\ResourceModel\RoomExtraOption;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    public $_idFieldName='id';
    protected function _construct()
    {
        $this->_init('Magenest\Cybergame\Model\RoomExtraOption','Magenest\Cybergame\Model\ResourceModel\RoomExtraOption');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
