<h2>Edit Test Address Information</h2>
<style>
    label {
        color: #0a0a0a;
    }
    input {
         width: 200px;

    }
    h2 {
         color: orangered;
    }
</style>
<?php $result = $block->getRecordEdit()?>
<form id="id" name="edit_test_form" method="post" action="/test/test/save/">
    <label for="id">Street: </label>
    <div>
        <input id="id" type="text" name="id" value="<?php echo $result['id']?>">
    </div>
    <label for="street">Street: </label>
    <div>
        <input id="street" type="text" name="street" value="<?php echo $result['street']?> ">
    </div>
    <label for="city">City: </label>
    <div>
        <input id="city" type="text" name="city" value="<?php echo $result['city']?>">
    </div>
    <label for="country">Country: </label>
    <div>
        <input id="country" type="text" name="country" value="<?php echo $result['country']?>">
    </div>
    <label for="region">Region: </label>
    <div>
        <input id="region" type="text" name="region" value="<?php echo $result['region']?>">
    </div>
    <label for="contact_name">Postcode: </label>
    <div>
        <input id="contact_name" type="text" name="contact_name" value="<?php echo $result['contact_name']?>">
    </div>
    <label for="telephone">Telephone: </label>
    <div>
        <input id="telephone" type="text" name="telephone" value="<?php echo $result['telephone']?>">
    </div>
    <label for="fax">Fax: </label>
    <div>
        <input id="fax" type="text" name="fax" value="<?php echo $result['fax']?>">
    </div>
    <label for="firstname">Firstname: </label>
    <div>
        <input id="firstname" type="text" name="firstname" value="<?php echo $result['firstname']?>">
    </div>
    <label for="lastname">Lastname: </label>
    <div>
        <input id="lastname" type="text" name="lastname" value="<?php echo $result['lastname']?>">
    </div>
    <label for="email">Email: </label>
    <div>
        <input id="email" type="text" name="email" value="<?php echo $result['email']?>"/>
    </div>
    <label for="prefix">Prefix: </label>
    <div>
        <input id="prefix" type="text" name="prefix" value="<?php echo $result['prefix']?>"/>
    </div>
    <input type="submit" value="Save" class="action primary"/>
</form>
