<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Quantity')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script>
    
    function changeFunction() {
        if (hasSpecial.length <= 0) {
            if (!isNaN(document.getElementById("qty").value) && document.getElementById("qty").value!= "") {
                var x = parseFloat(document.getElementById("qty").value);
                if (x < .25) {
                    x = .25;
                }
                var y = document.getElementsByClassName("price");
                var priceString = y[0].innerHTML;
                var originalPrice = parseFloat(priceString.substr(1));
                if (currentPrice != originalPrice && currentPrice != 0) {
                    finalPrice = currentPrice * x;
                }
                else {
                    finalPrice = originalPrice * x;
                }
                y[0].innerHTML = "$" + finalPrice.toFixed(2);
                currentPrice = finalPrice / x;
            }
        }
        else {
            if (!isNaN(document.getElementById("qty").value) && document.getElementById("qty").value!= "") {
                var x = parseFloat(document.getElementById("qty").value);
                if (x < .25) {
                    x = .25;
                }
                var y = document.getElementsByClassName("price");
                var priceString = y[1].innerHTML;
                var originalPrice = parseFloat(priceString.substr(22));
                if (currentPrice != originalPrice && currentPrice != 0) {
                    finalPrice = currentPrice * x;
                }
                else {
                    finalPrice = originalPrice * x;
                }
                y[1].innerHTML = "$" + finalPrice.toFixed(2);
                currentPrice = finalPrice / x;
            }
        }
    }
</script>
