<?php


namespace Magenest\Test\Model\ResourceModel\Test;


class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    public $_idFieldName = "id";
    protected function _construct()
    {
        $this->_init('Magenest\Test\Model\Test','Magenest\Test\Model\ResourceModel\Test');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
