<div>
    <label for="cybergame"><strong>Account name:</strong></label>
    <input width="50" type="text" id="cybergame" name="account_name">
    <div id="show_account_not_exist" hidden style="color: #007bdb; "></div>
</div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            $("#cybergame").blur(function (e) {
                e.preventDefault();
                let custom_link ="http://m234.local/cybergame/ajax/checkaccountname";
                let account_name = $("#cybergame").val();
                $.post(custom_link, {
                    name: account_name,
                }).done(function (data) {
                    $('#show_account_not_exist').html(data).show();
                }).fail(function (error)
                {
                   console.log(error)
                });

            });
        });
    });
</script>

