<?php


namespace Magenest\Test\Model;


use Magento\Framework\Model\Context;
use Magento\Framework\Math\Random;
use Magento\Framework\App\ObjectManager;

class Test extends \Magento\Framework\Model\AbstractModel
{
    public function __construct(Context $context,
                                \Magento\Framework\Registry $registry,
                                \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
                                \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
                                array $data = [])
    {
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }
    public function _construct()
    {
        $this->_init('Magenest\Test\Model\ResourceModel\Test');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
