<?php


namespace Magenest\Staff\Model;


use Magento\Framework\Model\Context;

class Staff extends \Magento\Framework\Model\AbstractModel
{
    public function __construct(Context $context,
                                \Magento\Framework\Registry $registry,
                                \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
                                \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
                                array $data = [])
    {
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }
    public function _construct()
    {
        $this->_init('Magenest\Staff\Model\ResourceModel\Staff');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
